modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Dinolek/LocateBiome/issues"
[[mods]]
modId="locatebiome"
version="${version}"
displayName="LocateBiome"
displayURL="https://minecraft.curseforge.com/projects/locatebiome"
authors="Dinolek, Prospector"
description='''
Adds command that give you ability to locate a biome.
'''

[[dependencies.locatebiome]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
